  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/zh/"

  [[main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/zh/post/"

  [[main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/zh/about/"

  [[main]]
  name = "Contact"
  weight = 400
  identifier = "contact"
  url = "/zh/contact/"